version: '2.4'
services:
  openconnect:
    image: ducmthai/openconnect:latest
    build:
      context: ./
    container_name: openconnect
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 172.25.21.1
      - 172.25.21.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./vpn.config:/vpn/vpn.config:ro
      - ./vpnpasswd1:/vpn/passwd1:ro
      - ./vpnpasswd2:/vpn/passwd2:ro
    env_file: .env
    networks:
      - openconnect
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}
    restart: always
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1    
      - net.ipv4.tcp_keepalive_intvl=45
      - net.ipv4.tcp_keepalive_probes=15
      - net.ipv4.tcp_keepalive_time=300      
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

networks:
  openconnect:
    external:
      name: openconnect
